Version 6.9.5
## Version 6.9.5 - April 24, 2023

  - **Fixed:** AspNetCoreSession: Prevent unnecessary intermittent error in console: "Error unprotecting the session cookie."

  - **Improved:** Used <LangVersion>9.0</LangVersion> to be able to inject module initializers.
    For example CheckTargetFramework method will throw error like below (some users still reference wrong DLLs):
    PlatformNotSupportedException: You currently referenced netstandard2.0 version of GleamTech.Common.dll which is
    not targeted for current runtime: .NET Framework 4.8.9139.0.
    Please reference net472 versions of GleamTech DLLs (found in folder Bin\net472) for .NET Framework 4.7.2+ projects.

  - **Improved:** Stability of AssemblyResolver.
    Ensured old log files are cleared, e.g. AssemblyResolver-xx.log and GleamTech-xx.log files.

  - **Changed:** AssemblyVersion is changed so recompile your project against the new DLLs (drop in to bin folder will not work).