Version 7.5.5
## Version 7.5.5 - March 30, 2025

  - **Added:** Better multi-platform suppport. Some conversions/viewing requires native dependencies which we already bundled
    in our DLL for win-x64 and win-x86 platforms. In addition to these, we now also bundle dependencies for these platforms:
    - win-arm64
    - linux-x64, linux-arm64
    - osx-x64, osx-arm64

    All win-* dependencies are bundled in our DLL and our AssemblyResolver will handle those, i.e automatically resolve them.

    However linux-* and osx-* dependencies are bundled only in our NuGet package in runtimes/<rid>/native folders,
    this is because it's nearly impossible to load/resolve native files in custom folders on non-Windows platforms (especially Linux).
    However .NET SDK handles this issue at build time: At build time, SDK will put runtimeTargets entries  in .deps.json file
    for each native file (.dll, .so, .dylib) that come/flow from a NuGet PackageReference.
    This way, .NET Runtime can resolve these native files by reading the .deps.json file.

    So in short, reference our NuGet package (not our DLL directly) especially if you are targeting linux-* and osx-*.

  - **Fixed:** Error when converting/viewing Email formats (e.g. .msg files) containing images:
    InvalidOperationException: The version of the native libSkiaSharp library (116.0) is incompatible with this version of SkiaSharp. Supported versions of the native libSkiaSharp library are in the range [88.1, 89.0).

  - **Improved:** Stability and performance of Portable formats.